[package]
name = "pizza-analysis-stconvert"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Simplified/Traditional Chinese conversion tokenizer for pizza-engine"
repository = "https://github.com/infinilabs/analysis-stconvert"


[features]
default = ["engine"]
engine = ["dep:pizza-engine"]

[dependencies]
pizza-engine = { path = "../../lib/engine", optional = true }